# Generated by Django 5.2.6 on 2025-09-18 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliothecaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('annee_edition', models.PositiveIntegerField()),
                ('consultable', models.BooleanField(default=True)),
                ('disponible', models.BooleanField(default=True)),
                ('theme', models.CharField(max_length=200)),
                ('media_type', models.CharField(choices=[('LIVRE', 'Livre'), ('DVD', 'DVD'), ('CD', 'CD')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JeuDePlateau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('annee_edition', models.PositiveIntegerField()),
                ('consultable', models.BooleanField(default=True)),
                ('createur', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('compte', models.CharField(max_length=50, unique=True)),
                ('bloque', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cd',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bibliothecaire.media')),
                ('artiste', models.CharField(max_length=100)),
                ('nb_piste', models.PositiveIntegerField(default=1)),
                ('duree_ecoute', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('bibliothecaire.media',),
        ),
        migrations.CreateModel(
            name='Dvd',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bibliothecaire.media')),
                ('realisateur', models.CharField(max_length=100)),
                ('duree', models.PositiveIntegerField()),
                ('histoire', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('bibliothecaire.media',),
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bibliothecaire.media')),
                ('auteur', models.CharField(max_length=100)),
                ('nb_page', models.PositiveIntegerField()),
                ('resume', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('bibliothecaire.media',),
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateField(auto_now_add=True)),
                ('date_retour', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('rendu', 'Rendu'), ('retard', 'En retard')], max_length=20)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='bibliothecaire.media')),
                ('emprunteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='bibliothecaire.membre')),
            ],
        ),
    ]
