# Generated by Django 5.2.6 on 2025-09-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cd',
            options={'verbose_name': 'CD', 'verbose_name_plural': 'CDs'},
        ),
        migrations.AlterModelOptions(
            name='dvd',
            options={'verbose_name': 'DVD', 'verbose_name_plural': 'DVDs'},
        ),
        migrations.AlterModelOptions(
            name='jeudeplateau',
            options={'verbose_name_plural': 'jeux de plateau'},
        ),
        migrations.AddField(
            model_name='jeudeplateau',
            name='age_min',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='jeudeplateau',
            name='categorie',
            field=models.CharField(default='Non classé', max_length=100),
        ),
        migrations.AddField(
            model_name='jeudeplateau',
            name='duree_partie',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='jeudeplateau',
            name='nb_joueur_max',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='jeudeplateau',
            name='nb_joueur_min',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='jeudeplateau',
            name='regle_consultable',
            field=models.BooleanField(default=False),
        ),
    ]
