# Generated by Django 5.2.6 on 2025-09-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0002_alter_cd_options_alter_dvd_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='statut',
            field=models.IntegerField(choices=[(0, 'En retard'), (1, 'En cours'), (2, 'Rendu')], default=1),
        ),
    ]
