# Generated by Django 5.2.6 on 2025-09-29 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0003_alter_emprunt_statut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bibliothecaire',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='jeudeplateau',
            old_name='titre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='titre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='membre',
            old_name='nom',
            new_name='name',
        ),
    ]
