# Generated by Django 5.2.6 on 2025-10-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0006_alter_jeudeplateau_annee_edition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeudeplateau',
            name='annee_edition',
            field=models.PositiveIntegerField(blank=True, help_text="Année d'édition si connue. Sinon laisser vide.", null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='annee_edition',
            field=models.PositiveIntegerField(blank=True, help_text="Année d'édition si connue. Sinon laisser vide.", null=True),
        ),
    ]
