# Generated by Django 5.2.6 on 2025-10-01 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0007_alter_jeudeplateau_annee_edition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd',
            name='duree_ecoute',
            field=models.PositiveIntegerField(blank=True, help_text="Durée d'écoute en minute (au moins une), ou laisser vide.", null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='cd',
            name='nb_piste',
            field=models.PositiveIntegerField(help_text='Nombre de pistes (au moins une).', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='duree',
            field=models.PositiveIntegerField(blank=True, help_text='Durée en minute (au moins une), ou laisser vide.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='livre',
            name='nb_page',
            field=models.PositiveIntegerField(blank=True, help_text='Nombre de pages (au moins une), ou laisser vide.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
