# Generated by Django 5.2.6 on 2025-10-03 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0008_alter_cd_duree_ecoute_alter_cd_nb_piste_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd',
            name='nb_piste',
            field=models.PositiveIntegerField(default=1, help_text='Nombre de pistes (au moins une).', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('NON_DEFINI', 'Non défini'), ('LIVRE', 'Livre'), ('DVD', 'DVD'), ('CD', 'CD')], default='NON_DEFINI', help_text="Type de média. 'NON_DEFINI' si aucun sous-type n'est instancié.", max_length=12),
        ),
    ]
