# Generated by Django 5.2.6 on 2025-10-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0009_alter_cd_nb_piste_alter_media_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeudeplateau',
            name='consultable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='media',
            name='consultable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='media',
            name='disponible',
            field=models.BooleanField(default=False),
        ),
    ]
