# Generated by Django 5.2.6 on 2025-10-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0010_alter_jeudeplateau_consultable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='bloque',
        ),
        migrations.AddField(
            model_name='membre',
            name='statut',
            field=models.IntegerField(choices=[(0, 'Non abonné'), (1, 'Abonné'), (2, 'Supprimé')], default=0),
        ),
    ]
