# Generated by Django 5.2.6 on 2025-11-24 18:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0011_remove_membre_bloque_membre_statut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliothecaire',
            name='role',
            field=models.IntegerField(choices=[(1, 'Administrateur'), (2, 'Gestionnaire')], default=2),
        ),
        migrations.AddField(
            model_name='bibliothecaire',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bibliothecaire', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jeudeplateau',
            name='age_min',
            field=models.PositiveIntegerField(default=8, help_text='Âge minimal pour jouer (au moins un an), ou laisser vide. Nombre par défaut de 8 ans.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='jeudeplateau',
            name='categorie',
            field=models.CharField(default='Non classé', help_text="Laisser vide si aucun classement connu. Est 'non classé' par défaut.", max_length=100),
        ),
        migrations.AlterField(
            model_name='jeudeplateau',
            name='consultable',
            field=models.BooleanField(default=False, help_text='Consultable si affichage à la consultation'),
        ),
        migrations.AlterField(
            model_name='jeudeplateau',
            name='duree_partie',
            field=models.PositiveIntegerField(default=30, help_text='Durée en minute (au moins une), ou laisser vide. Durée par défaut de 30 mn.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='jeudeplateau',
            name='nb_joueur_max',
            field=models.PositiveIntegerField(default=4, help_text='Nombre maximal de joueur (au moins un), ou laisser vide. Nombre par défaut de 4 joueurs.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='jeudeplateau',
            name='nb_joueur_min',
            field=models.PositiveIntegerField(default=2, help_text='Nombre minimal de joueur (au moins un), ou laisser vide. Nombre par défaut de 2 joueurs.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='jeudeplateau',
            name='regle_consultable',
            field=models.BooleanField(default=False, help_text='Consultable si affichage à la consultation'),
        ),
        migrations.AlterField(
            model_name='media',
            name='consultable',
            field=models.BooleanField(default=False, help_text='Consultable si affichage à la consultation'),
        ),
    ]
